import asyncio
import os
import sys

# Add backend dir to sys.path
sys.path.append(os.path.abspath('backend'))

from dotenv import load_dotenv
load_dotenv(os.path.join(os.path.abspath('backend'), '.env'))

from services.data_science_service import run_data_science_pipeline

def test():
    # We will use the last created temp folder's CSV
    csv_path = r"C:\Users\Tech\OneDrive\Desktop\multi Ai Agent\backend\temp\60ddbd92-bc8f-4ae2-aca7-91170b402de9\natures_mother_love_sales.csv"
    prompt = "Please analyze this sales data. Generate a bar chart showing the total revenue generated by each product, and provide a downloadable cleaned Excel file with the summary"
    
    result = run_data_science_pipeline(csv_path, prompt)
    print("TEXT RESPONSE:")
    print(result.text_response)
    print("\nHAS VISUALS:", result.has_data_visuals)
    print("\nLOGS:")
    print(result.execution_logs)

if __name__ == "__main__":
    test()
